# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 851aabd88438a53bd7dd602503e8f0780a667e42cd2ae83604b253419a3bc80175f4fc306b9d10bafb0fd29c46a6bd4f555ae9aae310563f855d625767863cbd

test:
  secret_key_base: ebe4088540f23e895a309c8404490fdfd3dcf7a1f0b23cd8c000182361b06dfcdd8cc2750558973f473e9be5a7d619fed0ed6c31bf518a5147c04b801f669721

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
